version: '3'
services:
  mongodb:
    image: arm64v8/mongo
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/arm64v8/mongodb

  knowledgekart:
    build: .
    environment:
      - JWT_ALGORITHM
      - JWT_SECRET_KEY
    depends_on:
      - mongodb
      - redis
    ports:
      - "8001:80"

  redis:
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mongodb:
  redis: